### ISSUE TITLE
Player dies mid air while placing blocks above the player for no reason

### ISSUE THREAD

**Issue by terukaaz** [huu-bo/micg#9]
[latest.log](https://github.com/huu-bo/micg/files/11185833/latest.log)
![image](https://user-images.githubusercontent.com/88054829/230784019-d1227807-3221-45bb-a064-029a6496a475.png)

**Comment by terukaaz** [comment]
feature question mark?

**Comment by huu-bo** [comment]
this is not a feature, it also happens when in/around falling blocks

**Comment by huu-bo** [comment]
fixed!
